import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

import '../../../flavors.dart';
import '../../router/router.dart';
import '../routes/routes.dart';
import '../services/services.dart';
import '../theme/theme.dart';

part 'adaptive/adaptive_value.dart';
part 'adaptive/breakpoints.dart';
part 'app_window_caption.dart';
part 'buttons/app_icon_button.dart';
part 'buttons/buttons.dart';
part 'chrome/page_progress.dart';
part 'chrome/reader_chrome_bar.dart';
part 'controls/app_dropdown_menu.dart';
part 'controls/app_popup_menu.dart';
part 'controls/app_segmented_control.dart';
part 'controls/app_slider.dart';
part 'controls/pin_button.dart';
part 'feedback/app_feedback.dart';
part 'overlay/app_sheet.dart';
part 'overlay/overlay_extensions.dart';
part 'settings/settings_row.dart';
part 'settings/settings_select_row.dart';
part 'typography/app_text.dart';
