import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:archive/archive_io.dart';
import 'package:dio/dio.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:get_it/get_it.dart';
import 'package:hive_ce/hive.dart';
import 'package:injectable/injectable.dart';
import 'package:just_audio/just_audio.dart';
import 'package:just_audio_media_kit/just_audio_media_kit.dart';
import 'package:logging/logging.dart';
import 'package:mupdf/mupdf.dart';
import 'package:native_dio_adapter/native_dio_adapter.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:readaway/gen/assets.gen.dart';
import 'package:rxdart/rxdart.dart';
import 'package:sherpa_onnx/sherpa_onnx.dart' as sherpa;
import 'package:wakelock_plus/wakelock_plus.dart';
import 'package:window_manager/window_manager.dart';

import '../../../flavors.dart';
import '../../features/settings/domain/models/reader_preferences.dart';
import '../error/errors.dart';
import '../models/models.dart';
import '../theme/theme.dart';

part 'app_lyfecycle_manager.dart';
part 'font_service.dart';
part 'http/http_service.dart';
part 'isolate_service.dart';
part 'logging_service.dart';
part 'lookup/lookup_service.dart';
part 'mupdf_service.dart';
part 'settings_service.dart';
part 'storage/hive/app_storage_service.dart';
part 'storage/hive/hive_config_service.dart';
part 'theme_service.dart';
part 'tts/device_tts_service.dart';
part 'tts/just_audio_service.dart';
part 'tts/reader_controller_service.dart';
part 'tts/sherpa_models.dart';
part 'tts/sherpa_onnx_tts_service.dart';
part 'tts/text_chunker_service.dart';
part 'tts/tts_models.dart';
part 'wakelock_service.dart';
part 'window_service.dart';
