import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:archive/archive_io.dart';
import 'package:audio_service/audio_service.dart';
import 'package:audio_service_mpris/audio_service_mpris.dart';
import 'package:audio_session/audio_session.dart';
import 'package:crypto/crypto.dart';
import 'package:dio/dio.dart';
import 'package:dio_cache_interceptor/dio_cache_interceptor.dart';
import 'package:dio_cache_interceptor_file_store/dio_cache_interceptor_file_store.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:get_it/get_it.dart';
import 'package:hive_ce/hive.dart';
import 'package:injectable/injectable.dart';
import 'package:just_audio/just_audio.dart';
import 'package:just_audio_media_kit/just_audio_media_kit.dart';
import 'package:logging/logging.dart';
import 'package:media_kit/media_kit.dart' as mk hide PlayerState;
import 'package:mupdf/mupdf.dart';
import 'package:native_dio_adapter/native_dio_adapter.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:rxdart/rxdart.dart';
import 'package:sherpa_onnx/sherpa_onnx.dart' as sherpa;
import 'package:wakelock_plus/wakelock_plus.dart';
import 'package:window_manager/window_manager.dart';

import '../../../flavors.dart';
import '../../features/settings/domain/models/reader_preferences.dart';
import '../error/errors.dart';
import '../models/models.dart';
import '../theme/theme.dart';

part 'app_lyfecycle_manager.dart';
part 'font_service.dart';
part 'http/http_service.dart';
part 'isolate_service.dart';
part 'just_audio/models/just_audio_models.dart';
part 'just_audio/just_audio_service.dart';
part 'logging_service.dart';
part 'lookup/lookup_service.dart';
part 'mupdf_service.dart';
part 'notification_service.dart';
part "package_info_service.dart";
part 'settings_service.dart';
part 'storage/hive/app_storage_service.dart';
part 'storage/hive/hive_config_service.dart';
part 'theme_service.dart';
part 'tts/sherpa/sherpa_isolate_worker_service.dart';
part 'tts/sherpa/sherpa_model_catalog.dart';
part 'tts/sherpa/sherpa_onnx_tts_service.dart';
part 'tts/sherpa/sherpa_tts_model_downloader.dart';
part 'tts/tts_chunker_service.dart';
part 'tts/tts_controller_service.dart';
part 'tts/tts_models.dart';
part 'wakelock_service.dart';
part 'window_service.dart';
