// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Opens an EPUB document and reads its metadata.
Future<RustDocumentMetadata> getEpubMetadata({required String path}) =>
    RustLib.instance.api.crateApiDocumentGetEpubMetadata(path: path);

/// Returns the total number of sections (spine items) in the EPUB.
Future<BigInt> getEpubSectionCount({required String path}) =>
    RustLib.instance.api.crateApiDocumentGetEpubSectionCount(path: path);

/// Returns the ordered list of spine item hrefs in the EPUB.
Future<List<String>> getEpubSpineHrefs({required String path}) =>
    RustLib.instance.api.crateApiDocumentGetEpubSpineHrefs(path: path);

/// Reads the HTML content of a specific section from the EPUB (async).
Future<String> readEpubSection({
  required String path,
  required BigInt sectionIndex,
}) => RustLib.instance.api.crateApiDocumentReadEpubSection(
  path: path,
  sectionIndex: sectionIndex,
);

/// Reads the HTML content of a specific section from the EPUB synchronously.
String readEpubSectionSync({
  required String path,
  required BigInt sectionIndex,
}) => RustLib.instance.api.crateApiDocumentReadEpubSectionSync(
  path: path,
  sectionIndex: sectionIndex,
);

/// Reads an arbitrary resource (e.g. image, stylesheet) from the EPUB archive (async).
Future<Uint8List> readEpubResource({
  required String path,
  required String resourcePath,
}) => RustLib.instance.api.crateApiDocumentReadEpubResource(
  path: path,
  resourcePath: resourcePath,
);

/// Reads an arbitrary resource from the EPUB archive synchronously.
Uint8List readEpubResourceSync({
  required String path,
  required String resourcePath,
}) => RustLib.instance.api.crateApiDocumentReadEpubResourceSync(
  path: path,
  resourcePath: resourcePath,
);

/// Returns the hierarchical Table of Contents (TOC) of the EPUB.
Future<List<RustTocItem>> getEpubToc({required String path}) =>
    RustLib.instance.api.crateApiDocumentGetEpubToc(path: path);

/// Resolves an internal link target [href] to a section index, if found.
Future<int?> resolveEpubSpineHref({
  required String path,
  required String href,
}) => RustLib.instance.api.crateApiDocumentResolveEpubSpineHref(
  path: path,
  href: href,
);

/// Opens a CBZ comic and returns the total page count.
Future<BigInt> getCbzPageCount({required String path}) =>
    RustLib.instance.api.crateApiDocumentGetCbzPageCount(path: path);

/// Returns all image page entry paths in the CBZ archive.
List<String> getCbzPagePaths({required String path}) =>
    RustLib.instance.api.crateApiDocumentGetCbzPagePaths(path: path);

/// Reads a specific page image bytes from the CBZ archive (async).
Future<Uint8List> readCbzPageImage({
  required String path,
  required BigInt pageIndex,
}) => RustLib.instance.api.crateApiDocumentReadCbzPageImage(
  path: path,
  pageIndex: pageIndex,
);

/// Reads a specific page image bytes from the CBZ archive synchronously.
Uint8List readCbzPageImageSync({
  required String path,
  required BigInt pageIndex,
}) => RustLib.instance.api.crateApiDocumentReadCbzPageImageSync(
  path: path,
  pageIndex: pageIndex,
);

/// Reads an arbitrary asset from the CBZ archive synchronously.
Uint8List readCbzAssetSync({required String path, required String assetPath}) =>
    RustLib.instance.api.crateApiDocumentReadCbzAssetSync(
      path: path,
      assetPath: assetPath,
    );
