// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class RustDocumentMetadata with _$RustDocumentMetadata {
  const factory RustDocumentMetadata({
    String? title,
    String? author,
    String? language,
    String? identifier,
    String? publisher,
    String? description,
    String? coverImagePath,
  }) = _RustDocumentMetadata;
}

class RustExtractedContent {
  final String displayText;
  final String speechText;
  final List<RustFootnote> footnotes;

  const RustExtractedContent({
    required this.displayText,
    required this.speechText,
    required this.footnotes,
  });

  @override
  int get hashCode =>
      displayText.hashCode ^ speechText.hashCode ^ footnotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustExtractedContent &&
          runtimeType == other.runtimeType &&
          displayText == other.displayText &&
          speechText == other.speechText &&
          footnotes == other.footnotes;
}

class RustFootnote {
  final String id;
  final String contentHtml;
  final String footnoteType;

  const RustFootnote({
    required this.id,
    required this.contentHtml,
    required this.footnoteType,
  });

  @override
  int get hashCode =>
      id.hashCode ^ contentHtml.hashCode ^ footnoteType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustFootnote &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contentHtml == other.contentHtml &&
          footnoteType == other.footnoteType;
}

class RustTocItem {
  final String title;
  final String href;
  final BigInt level;
  final int? chapterIndex;
  final List<RustTocItem> children;

  const RustTocItem({
    required this.title,
    required this.href,
    required this.level,
    this.chapterIndex,
    required this.children,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      href.hashCode ^
      level.hashCode ^
      chapterIndex.hashCode ^
      children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTocItem &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          href == other.href &&
          level == other.level &&
          chapterIndex == other.chapterIndex &&
          children == other.children;
}

class RustTtsChunk {
  final String id;
  final int sectionIndex;
  final int sentenceIndex;
  final String displayText;
  final String spokenText;
  final BigInt startOffset;
  final BigInt endOffset;
  final int estimatedDurationMs;
  final bool isParagraphEnd;
  final int paragraphIndex;

  const RustTtsChunk({
    required this.id,
    required this.sectionIndex,
    required this.sentenceIndex,
    required this.displayText,
    required this.spokenText,
    required this.startOffset,
    required this.endOffset,
    required this.estimatedDurationMs,
    required this.isParagraphEnd,
    required this.paragraphIndex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sectionIndex.hashCode ^
      sentenceIndex.hashCode ^
      displayText.hashCode ^
      spokenText.hashCode ^
      startOffset.hashCode ^
      endOffset.hashCode ^
      estimatedDurationMs.hashCode ^
      isParagraphEnd.hashCode ^
      paragraphIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTtsChunk &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sectionIndex == other.sectionIndex &&
          sentenceIndex == other.sentenceIndex &&
          displayText == other.displayText &&
          spokenText == other.spokenText &&
          startOffset == other.startOffset &&
          endOffset == other.endOffset &&
          estimatedDurationMs == other.estimatedDurationMs &&
          isParagraphEnd == other.isParagraphEnd &&
          paragraphIndex == other.paragraphIndex;
}
