// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Preprocesses raw HTML or plain text into normalized TTS chunks for speech synthesis.
/// Performs:
/// 1. HTML tag removal and footnote isolation (if HTML).
/// 2. Unicode NFKC normalization and zero-width character stripping.
/// 3. Sentence boundary segmentation with abbreviation disambiguation (`sentencex`).
/// 4. Spoken text expansion ($42.50 -> forty-two dollars and fifty cents, Dr. -> Doctor).
/// 5. Phonetic transliteration with `deunicode`.
/// 6. Duration estimation and character offset tracking.
List<RustTtsChunk> preprocessTextForTts({
  required String text,
  required int sectionIndex,
  String? language,
  required bool isHtml,
}) => RustLib.instance.api.crateApiTtsPreprocessTextForTts(
  text: text,
  sectionIndex: sectionIndex,
  language: language,
  isHtml: isHtml,
);

/// Normalizes a single string for speech synthesis (number expansion, abbreviations, ASCII transliteration).
String normalizeSingleTextForSpeech({required String text}) =>
    RustLib.instance.api.crateApiTtsNormalizeSingleTextForSpeech(text: text);

/// Extracts clean display text, speech text, and footnotes from HTML.
RustExtractedContent extractHtmlContent({required String html}) =>
    RustLib.instance.api.crateApiTtsExtractHtmlContent(html: html);
