part of 'models.dart';

/// An extracted chapter or section from a plain text document.
@freezed
abstract class TxtChapter with _$TxtChapter {
  const factory TxtChapter({
    /// Zero-based sequential chapter index.
    required int index,

    /// Chapter or section title.
    required String title,

    /// Clean semantic HTML content for this chapter (`<h2>...</h2><p>...</p>`).
    required String contentHtml,

    /// True if this chapter represents a volume or book partition.
    @Default(false) bool isVolume,

    /// True if this chapter title was detected from a heading regex;
    /// false if it was generated by fallback paragraph chunking.
    @Default(true) bool detected,
  }) = _TxtChapter;

  factory TxtChapter.fromJson(Map<String, dynamic> json) =>
      _$TxtChapterFromJson(json);
}
