// AUTO-GENERATED by ffigen. Do not edit.
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// FFI bindings for mupdf_wrapper.h
class MupdfBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MupdfBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MupdfBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int mupdf_authenticate_password(
    mupdf_context ctx,
    mupdf_document doc,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _mupdf_authenticate_password(
      ctx,
      doc,
      password,
    );
  }

  late final _mupdf_authenticate_passwordPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(mupdf_context, mupdf_document, ffi.Pointer<ffi.Char>)
        >
      >('mupdf_authenticate_password');
  late final _mupdf_authenticate_password = _mupdf_authenticate_passwordPtr
      .asFunction<
        int Function(mupdf_context, mupdf_document, ffi.Pointer<ffi.Char>)
      >();

  int mupdf_count_chapter_pages(
    mupdf_context ctx,
    mupdf_document doc,
    int chapter,
  ) {
    return _mupdf_count_chapter_pages(
      ctx,
      doc,
      chapter,
    );
  }

  late final _mupdf_count_chapter_pagesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(mupdf_context, mupdf_document, ffi.Int)
        >
      >('mupdf_count_chapter_pages');
  late final _mupdf_count_chapter_pages = _mupdf_count_chapter_pagesPtr
      .asFunction<int Function(mupdf_context, mupdf_document, int)>();

  int mupdf_count_chapters(
    mupdf_context ctx,
    mupdf_document doc,
  ) {
    return _mupdf_count_chapters(
      ctx,
      doc,
    );
  }

  late final _mupdf_count_chaptersPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_document)>
      >('mupdf_count_chapters');
  late final _mupdf_count_chapters = _mupdf_count_chaptersPtr
      .asFunction<int Function(mupdf_context, mupdf_document)>();

  int mupdf_count_pages(
    mupdf_context ctx,
    mupdf_document doc,
  ) {
    return _mupdf_count_pages(
      ctx,
      doc,
    );
  }

  late final _mupdf_count_pagesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_document)>
      >('mupdf_count_pages');
  late final _mupdf_count_pages = _mupdf_count_pagesPtr
      .asFunction<int Function(mupdf_context, mupdf_document)>();

  void mupdf_drop_context(
    mupdf_context ctx,
  ) {
    return _mupdf_drop_context(
      ctx,
    );
  }

  late final _mupdf_drop_contextPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(mupdf_context)>>(
        'mupdf_drop_context',
      );
  late final _mupdf_drop_context = _mupdf_drop_contextPtr
      .asFunction<void Function(mupdf_context)>();

  void mupdf_drop_document(
    mupdf_context ctx,
    mupdf_document doc,
  ) {
    return _mupdf_drop_document(
      ctx,
      doc,
    );
  }

  late final _mupdf_drop_documentPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(mupdf_context, mupdf_document)>
      >('mupdf_drop_document');
  late final _mupdf_drop_document = _mupdf_drop_documentPtr
      .asFunction<void Function(mupdf_context, mupdf_document)>();

  void mupdf_drop_page(
    mupdf_context ctx,
    mupdf_page page,
  ) {
    return _mupdf_drop_page(
      ctx,
      page,
    );
  }

  late final _mupdf_drop_pagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(mupdf_context, mupdf_page)>>(
        'mupdf_drop_page',
      );
  late final _mupdf_drop_page = _mupdf_drop_pagePtr
      .asFunction<void Function(mupdf_context, mupdf_page)>();

  void mupdf_drop_pixmap(
    mupdf_context ctx,
    mupdf_pixmap pix,
  ) {
    return _mupdf_drop_pixmap(
      ctx,
      pix,
    );
  }

  late final _mupdf_drop_pixmapPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(mupdf_context, mupdf_pixmap)>
      >('mupdf_drop_pixmap');
  late final _mupdf_drop_pixmap = _mupdf_drop_pixmapPtr
      .asFunction<void Function(mupdf_context, mupdf_pixmap)>();

  ffi.Pointer<ffi.Char> mupdf_extract_html(
    mupdf_context ctx,
    mupdf_page page,
  ) {
    return _mupdf_extract_html(
      ctx,
      page,
    );
  }

  late final _mupdf_extract_htmlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(mupdf_context, mupdf_page)
        >
      >('mupdf_extract_html');
  late final _mupdf_extract_html = _mupdf_extract_htmlPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(mupdf_context, mupdf_page)>();

  ffi.Pointer<ffi.Char> mupdf_extract_text(
    mupdf_context ctx,
    mupdf_page page,
  ) {
    return _mupdf_extract_text(
      ctx,
      page,
    );
  }

  late final _mupdf_extract_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(mupdf_context, mupdf_page)
        >
      >('mupdf_extract_text');
  late final _mupdf_extract_text = _mupdf_extract_textPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(mupdf_context, mupdf_page)>();

  void mupdf_free_floats(
    ffi.Pointer<ffi.Float> ptr,
  ) {
    return _mupdf_free_floats(
      ptr,
    );
  }

  late final _mupdf_free_floatsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Float>)>>(
        'mupdf_free_floats',
      );
  late final _mupdf_free_floats = _mupdf_free_floatsPtr
      .asFunction<void Function(ffi.Pointer<ffi.Float>)>();

  void mupdf_free_string(
    mupdf_context ctx,
    ffi.Pointer<ffi.Char> str,
  ) {
    return _mupdf_free_string(
      ctx,
      str,
    );
  }

  late final _mupdf_free_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(mupdf_context, ffi.Pointer<ffi.Char>)
        >
      >('mupdf_free_string');
  late final _mupdf_free_string = _mupdf_free_stringPtr
      .asFunction<void Function(mupdf_context, ffi.Pointer<ffi.Char>)>();

  int mupdf_has_permission(
    mupdf_context ctx,
    mupdf_document doc,
    int permission,
  ) {
    return _mupdf_has_permission(
      ctx,
      doc,
      permission,
    );
  }

  late final _mupdf_has_permissionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(mupdf_context, mupdf_document, ffi.Int)
        >
      >('mupdf_has_permission');
  late final _mupdf_has_permission = _mupdf_has_permissionPtr
      .asFunction<int Function(mupdf_context, mupdf_document, int)>();

  int mupdf_is_reflowable(
    mupdf_context ctx,
    mupdf_document doc,
  ) {
    return _mupdf_is_reflowable(
      ctx,
      doc,
    );
  }

  late final _mupdf_is_reflowablePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_document)>
      >('mupdf_is_reflowable');
  late final _mupdf_is_reflowable = _mupdf_is_reflowablePtr
      .asFunction<int Function(mupdf_context, mupdf_document)>();

  ffi.Pointer<ffi.Char> mupdf_last_error(
    mupdf_context ctx,
  ) {
    return _mupdf_last_error(
      ctx,
    );
  }

  late final _mupdf_last_errorPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(mupdf_context)>
      >('mupdf_last_error');
  late final _mupdf_last_error = _mupdf_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(mupdf_context)>();

  int mupdf_layout_document(
    mupdf_context ctx,
    mupdf_document doc,
    double width,
    double height,
    double em,
  ) {
    return _mupdf_layout_document(
      ctx,
      doc,
      width,
      height,
      em,
    );
  }

  late final _mupdf_layout_documentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            mupdf_context,
            mupdf_document,
            ffi.Float,
            ffi.Float,
            ffi.Float,
          )
        >
      >('mupdf_layout_document');
  late final _mupdf_layout_document = _mupdf_layout_documentPtr
      .asFunction<
        int Function(mupdf_context, mupdf_document, double, double, double)
      >();

  mupdf_page mupdf_load_chapter_page(
    mupdf_context ctx,
    mupdf_document doc,
    int chapter,
    int page,
  ) {
    return _mupdf_load_chapter_page(
      ctx,
      doc,
      chapter,
      page,
    );
  }

  late final _mupdf_load_chapter_pagePtr =
      _lookup<
        ffi.NativeFunction<
          mupdf_page Function(mupdf_context, mupdf_document, ffi.Int, ffi.Int)
        >
      >('mupdf_load_chapter_page');
  late final _mupdf_load_chapter_page = _mupdf_load_chapter_pagePtr
      .asFunction<
        mupdf_page Function(mupdf_context, mupdf_document, int, int)
      >();

  mupdf_page mupdf_load_page(
    mupdf_context ctx,
    mupdf_document doc,
    int number,
  ) {
    return _mupdf_load_page(
      ctx,
      doc,
      number,
    );
  }

  late final _mupdf_load_pagePtr =
      _lookup<
        ffi.NativeFunction<
          mupdf_page Function(mupdf_context, mupdf_document, ffi.Int)
        >
      >('mupdf_load_page');
  late final _mupdf_load_page = _mupdf_load_pagePtr
      .asFunction<mupdf_page Function(mupdf_context, mupdf_document, int)>();

  int mupdf_lookup_metadata(
    mupdf_context ctx,
    mupdf_document doc,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> buf,
    int bufsize,
  ) {
    return _mupdf_lookup_metadata(
      ctx,
      doc,
      key,
      buf,
      bufsize,
    );
  }

  late final _mupdf_lookup_metadataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            mupdf_context,
            mupdf_document,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('mupdf_lookup_metadata');
  late final _mupdf_lookup_metadata = _mupdf_lookup_metadataPtr
      .asFunction<
        int Function(
          mupdf_context,
          mupdf_document,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  int mupdf_needs_password(
    mupdf_context ctx,
    mupdf_document doc,
  ) {
    return _mupdf_needs_password(
      ctx,
      doc,
    );
  }

  late final _mupdf_needs_passwordPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_document)>
      >('mupdf_needs_password');
  late final _mupdf_needs_password = _mupdf_needs_passwordPtr
      .asFunction<int Function(mupdf_context, mupdf_document)>();

  mupdf_context mupdf_new_context() {
    return _mupdf_new_context();
  }

  late final _mupdf_new_contextPtr =
      _lookup<ffi.NativeFunction<mupdf_context Function()>>(
        'mupdf_new_context',
      );
  late final _mupdf_new_context = _mupdf_new_contextPtr
      .asFunction<mupdf_context Function()>();

  mupdf_pixmap mupdf_new_pixmap_from_page(
    mupdf_context ctx,
    mupdf_page page,
    double scale_x,
    double scale_y,
    int alpha,
  ) {
    return _mupdf_new_pixmap_from_page(
      ctx,
      page,
      scale_x,
      scale_y,
      alpha,
    );
  }

  late final _mupdf_new_pixmap_from_pagePtr =
      _lookup<
        ffi.NativeFunction<
          mupdf_pixmap Function(
            mupdf_context,
            mupdf_page,
            ffi.Float,
            ffi.Float,
            ffi.Int,
          )
        >
      >('mupdf_new_pixmap_from_page');
  late final _mupdf_new_pixmap_from_page = _mupdf_new_pixmap_from_pagePtr
      .asFunction<
        mupdf_pixmap Function(mupdf_context, mupdf_page, double, double, int)
      >();

  mupdf_pixmap mupdf_new_pixmap_from_page_cs(
    mupdf_context ctx,
    mupdf_page page,
    double scale_x,
    double scale_y,
    int alpha,
    int cs,
  ) {
    return _mupdf_new_pixmap_from_page_cs(
      ctx,
      page,
      scale_x,
      scale_y,
      alpha,
      cs,
    );
  }

  late final _mupdf_new_pixmap_from_page_csPtr =
      _lookup<
        ffi.NativeFunction<
          mupdf_pixmap Function(
            mupdf_context,
            mupdf_page,
            ffi.Float,
            ffi.Float,
            ffi.Int,
            ffi.Int,
          )
        >
      >('mupdf_new_pixmap_from_page_cs');
  late final _mupdf_new_pixmap_from_page_cs = _mupdf_new_pixmap_from_page_csPtr
      .asFunction<
        mupdf_pixmap Function(
          mupdf_context,
          mupdf_page,
          double,
          double,
          int,
          int,
        )
      >();

  mupdf_document mupdf_open_document(
    mupdf_context ctx,
    ffi.Pointer<ffi.Char> filename,
  ) {
    return _mupdf_open_document(
      ctx,
      filename,
    );
  }

  late final _mupdf_open_documentPtr =
      _lookup<
        ffi.NativeFunction<
          mupdf_document Function(mupdf_context, ffi.Pointer<ffi.Char>)
        >
      >('mupdf_open_document');
  late final _mupdf_open_document = _mupdf_open_documentPtr
      .asFunction<
        mupdf_document Function(mupdf_context, ffi.Pointer<ffi.Char>)
      >();

  mupdf_document mupdf_open_document_from_data(
    mupdf_context ctx,
    ffi.Pointer<ffi.Uint8> data,
    int size,
  ) {
    return _mupdf_open_document_from_data(
      ctx,
      data,
      size,
    );
  }

  late final _mupdf_open_document_from_dataPtr =
      _lookup<
        ffi.NativeFunction<
          mupdf_document Function(
            mupdf_context,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int64,
          )
        >
      >('mupdf_open_document_from_data');
  late final _mupdf_open_document_from_data = _mupdf_open_document_from_dataPtr
      .asFunction<
        mupdf_document Function(mupdf_context, ffi.Pointer<ffi.Uint8>, int)
      >();

  int mupdf_outline_flatten(
    mupdf_context ctx,
    mupdf_document doc,
    ffi.Pointer<ffi.Pointer<mupdf_outline_item>> items,
  ) {
    return _mupdf_outline_flatten(
      ctx,
      doc,
      items,
    );
  }

  late final _mupdf_outline_flattenPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            mupdf_context,
            mupdf_document,
            ffi.Pointer<ffi.Pointer<mupdf_outline_item>>,
          )
        >
      >('mupdf_outline_flatten');
  late final _mupdf_outline_flatten = _mupdf_outline_flattenPtr
      .asFunction<
        int Function(
          mupdf_context,
          mupdf_document,
          ffi.Pointer<ffi.Pointer<mupdf_outline_item>>,
        )
      >();

  void mupdf_outline_free(
    ffi.Pointer<mupdf_outline_item> items,
    int count,
  ) {
    return _mupdf_outline_free(
      items,
      count,
    );
  }

  late final _mupdf_outline_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<mupdf_outline_item>, ffi.Int)
        >
      >('mupdf_outline_free');
  late final _mupdf_outline_free = _mupdf_outline_freePtr
      .asFunction<void Function(ffi.Pointer<mupdf_outline_item>, int)>();

  int mupdf_page_bound_box(
    mupdf_context ctx,
    mupdf_page page,
    ffi.Pointer<ffi.Float> width,
    ffi.Pointer<ffi.Float> height,
  ) {
    return _mupdf_page_bound_box(
      ctx,
      page,
      width,
      height,
    );
  }

  late final _mupdf_page_bound_boxPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            mupdf_context,
            mupdf_page,
            ffi.Pointer<ffi.Float>,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('mupdf_page_bound_box');
  late final _mupdf_page_bound_box = _mupdf_page_bound_boxPtr
      .asFunction<
        int Function(
          mupdf_context,
          mupdf_page,
          ffi.Pointer<ffi.Float>,
          ffi.Pointer<ffi.Float>,
        )
      >();

  double mupdf_page_height(
    mupdf_context ctx,
    mupdf_page page,
  ) {
    return _mupdf_page_height(
      ctx,
      page,
    );
  }

  late final _mupdf_page_heightPtr =
      _lookup<
        ffi.NativeFunction<ffi.Float Function(mupdf_context, mupdf_page)>
      >('mupdf_page_height');
  late final _mupdf_page_height = _mupdf_page_heightPtr
      .asFunction<double Function(mupdf_context, mupdf_page)>();

  int mupdf_page_label(
    mupdf_context ctx,
    mupdf_page page,
    ffi.Pointer<ffi.Char> buf,
    int bufsize,
  ) {
    return _mupdf_page_label(
      ctx,
      page,
      buf,
      bufsize,
    );
  }

  late final _mupdf_page_labelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            mupdf_context,
            mupdf_page,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('mupdf_page_label');
  late final _mupdf_page_label = _mupdf_page_labelPtr
      .asFunction<
        int Function(mupdf_context, mupdf_page, ffi.Pointer<ffi.Char>, int)
      >();

  double mupdf_page_width(
    mupdf_context ctx,
    mupdf_page page,
  ) {
    return _mupdf_page_width(
      ctx,
      page,
    );
  }

  late final _mupdf_page_widthPtr =
      _lookup<
        ffi.NativeFunction<ffi.Float Function(mupdf_context, mupdf_page)>
      >('mupdf_page_width');
  late final _mupdf_page_width = _mupdf_page_widthPtr
      .asFunction<double Function(mupdf_context, mupdf_page)>();

  int mupdf_pixmap_components(
    mupdf_context ctx,
    mupdf_pixmap pix,
  ) {
    return _mupdf_pixmap_components(
      ctx,
      pix,
    );
  }

  late final _mupdf_pixmap_componentsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_pixmap)>
      >('mupdf_pixmap_components');
  late final _mupdf_pixmap_components = _mupdf_pixmap_componentsPtr
      .asFunction<int Function(mupdf_context, mupdf_pixmap)>();

  int mupdf_pixmap_height(
    mupdf_context ctx,
    mupdf_pixmap pix,
  ) {
    return _mupdf_pixmap_height(
      ctx,
      pix,
    );
  }

  late final _mupdf_pixmap_heightPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_pixmap)>
      >('mupdf_pixmap_height');
  late final _mupdf_pixmap_height = _mupdf_pixmap_heightPtr
      .asFunction<int Function(mupdf_context, mupdf_pixmap)>();

  ffi.Pointer<ffi.UnsignedChar> mupdf_pixmap_samples(
    mupdf_context ctx,
    mupdf_pixmap pix,
  ) {
    return _mupdf_pixmap_samples(
      ctx,
      pix,
    );
  }

  late final _mupdf_pixmap_samplesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.UnsignedChar> Function(mupdf_context, mupdf_pixmap)
        >
      >('mupdf_pixmap_samples');
  late final _mupdf_pixmap_samples = _mupdf_pixmap_samplesPtr
      .asFunction<
        ffi.Pointer<ffi.UnsignedChar> Function(mupdf_context, mupdf_pixmap)
      >();

  int mupdf_pixmap_stride(
    mupdf_context ctx,
    mupdf_pixmap pix,
  ) {
    return _mupdf_pixmap_stride(
      ctx,
      pix,
    );
  }

  late final _mupdf_pixmap_stridePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_pixmap)>
      >('mupdf_pixmap_stride');
  late final _mupdf_pixmap_stride = _mupdf_pixmap_stridePtr
      .asFunction<int Function(mupdf_context, mupdf_pixmap)>();

  int mupdf_pixmap_width(
    mupdf_context ctx,
    mupdf_pixmap pix,
  ) {
    return _mupdf_pixmap_width(
      ctx,
      pix,
    );
  }

  late final _mupdf_pixmap_widthPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(mupdf_context, mupdf_pixmap)>
      >('mupdf_pixmap_width');
  late final _mupdf_pixmap_width = _mupdf_pixmap_widthPtr
      .asFunction<int Function(mupdf_context, mupdf_pixmap)>();

  int mupdf_search_page(
    mupdf_context ctx,
    mupdf_page page,
    ffi.Pointer<ffi.Char> needle,
    ffi.Pointer<ffi.Int> hit_count,
  ) {
    return _mupdf_search_page(
      ctx,
      page,
      needle,
      hit_count,
    );
  }

  late final _mupdf_search_pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            mupdf_context,
            mupdf_page,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('mupdf_search_page');
  late final _mupdf_search_page = _mupdf_search_pagePtr
      .asFunction<
        int Function(
          mupdf_context,
          mupdf_page,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  ffi.Pointer<ffi.Float> mupdf_search_page_quads(
    mupdf_context ctx,
    mupdf_page page,
    ffi.Pointer<ffi.Char> needle,
    ffi.Pointer<ffi.Int> hit_count,
  ) {
    return _mupdf_search_page_quads(
      ctx,
      page,
      needle,
      hit_count,
    );
  }

  late final _mupdf_search_page_quadsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Float> Function(
            mupdf_context,
            mupdf_page,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('mupdf_search_page_quads');
  late final _mupdf_search_page_quads = _mupdf_search_page_quadsPtr
      .asFunction<
        ffi.Pointer<ffi.Float> Function(
          mupdf_context,
          mupdf_page,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int>,
        )
      >();
}

const int MUPDF_ERR_FORMAT = 4;

const int MUPDF_ERR_GENERIC = 1;

const int MUPDF_ERR_IO = 3;

const int MUPDF_ERR_MEMORY = 2;

const int MUPDF_ERR_PASSWORD = 5;

const int MUPDF_OK = 0;

typedef mupdf_context = ffi.Pointer<ffi.Void>;
typedef mupdf_document = ffi.Pointer<ffi.Void>;

final class mupdf_outline_item extends ffi.Struct {
  external ffi.Pointer<ffi.Char> title;

  external ffi.Pointer<ffi.Char> uri;

  @ffi.Int()
  external int chapter;

  @ffi.Int()
  external int page;

  @ffi.Int()
  external int level;

  @ffi.Int()
  external int is_open;

  static ffi.Pointer<mupdf_outline_item> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> title,
    required ffi.Pointer<ffi.Char> uri,
    required int chapter,
    required int page,
    required int level,
    required int is_open,
  }) => $allocator<mupdf_outline_item>()
    ..ref.title = title
    ..ref.uri = uri
    ..ref.chapter = chapter
    ..ref.page = page
    ..ref.level = level
    ..ref.is_open = is_open;
}

typedef mupdf_page = ffi.Pointer<ffi.Void>;
typedef mupdf_pixmap = ffi.Pointer<ffi.Void>;
