// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/document.dart';
import 'api/init.dart';
import 'api/models.dart';
import 'api/tts.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<RustLogEntry> dco_decode_StreamSink_rust_log_entry_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RustFootnote> dco_decode_list_rust_footnote(dynamic raw);

  @protected
  List<RustTocItem> dco_decode_list_rust_toc_item(dynamic raw);

  @protected
  List<RustTtsChunk> dco_decode_list_rust_tts_chunk(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  RustDocumentMetadata dco_decode_rust_document_metadata(dynamic raw);

  @protected
  RustExtractedContent dco_decode_rust_extracted_content(dynamic raw);

  @protected
  RustFootnote dco_decode_rust_footnote(dynamic raw);

  @protected
  RustLogEntry dco_decode_rust_log_entry(dynamic raw);

  @protected
  RustTocItem dco_decode_rust_toc_item(dynamic raw);

  @protected
  RustTtsChunk dco_decode_rust_tts_chunk(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<RustLogEntry> sse_decode_StreamSink_rust_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RustFootnote> sse_decode_list_rust_footnote(
    SseDeserializer deserializer,
  );

  @protected
  List<RustTocItem> sse_decode_list_rust_toc_item(SseDeserializer deserializer);

  @protected
  List<RustTtsChunk> sse_decode_list_rust_tts_chunk(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  RustDocumentMetadata sse_decode_rust_document_metadata(
    SseDeserializer deserializer,
  );

  @protected
  RustExtractedContent sse_decode_rust_extracted_content(
    SseDeserializer deserializer,
  );

  @protected
  RustFootnote sse_decode_rust_footnote(SseDeserializer deserializer);

  @protected
  RustLogEntry sse_decode_rust_log_entry(SseDeserializer deserializer);

  @protected
  RustTocItem sse_decode_rust_toc_item(SseDeserializer deserializer);

  @protected
  RustTtsChunk sse_decode_rust_tts_chunk(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_rust_log_entry_Sse(
    RustStreamSink<RustLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_footnote(
    List<RustFootnote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_toc_item(
    List<RustTocItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_tts_chunk(
    List<RustTtsChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_rust_document_metadata(
    RustDocumentMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_extracted_content(
    RustExtractedContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_footnote(RustFootnote self, SseSerializer serializer);

  @protected
  void sse_encode_rust_log_entry(RustLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_rust_toc_item(RustTocItem self, SseSerializer serializer);

  @protected
  void sse_encode_rust_tts_chunk(RustTtsChunk self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
