// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/document.dart';
import 'api/init.dart';
import 'api/models.dart';
import 'api/tts.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1065918602;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'readaway_core_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<RustLogEntry> crateApiInitCreateLogStream();

  RustExtractedContent crateApiTtsExtractHtmlContent({required String html});

  Future<BigInt> crateApiDocumentGetCbzPageCount({required String path});

  List<String> crateApiDocumentGetCbzPagePaths({required String path});

  Future<RustDocumentMetadata> crateApiDocumentGetEpubMetadata({
    required String path,
  });

  Future<BigInt> crateApiDocumentGetEpubSectionCount({required String path});

  Future<List<String>> crateApiDocumentGetEpubSpineHrefs({
    required String path,
  });

  Future<List<RustTocItem>> crateApiDocumentGetEpubToc({required String path});

  Future<void> crateApiInitInitApp();

  bool crateApiInitIsRustInitialized();

  String crateApiTtsNormalizeSingleTextForSpeech({required String text});

  List<RustTtsChunk> crateApiTtsPreprocessTextForTts({
    required String text,
    required int sectionIndex,
    String? language,
    required bool isHtml,
  });

  Uint8List crateApiDocumentReadCbzAssetSync({
    required String path,
    required String assetPath,
  });

  Future<Uint8List> crateApiDocumentReadCbzPageImage({
    required String path,
    required BigInt pageIndex,
  });

  Uint8List crateApiDocumentReadCbzPageImageSync({
    required String path,
    required BigInt pageIndex,
  });

  Future<Uint8List> crateApiDocumentReadEpubResource({
    required String path,
    required String resourcePath,
  });

  Uint8List crateApiDocumentReadEpubResourceSync({
    required String path,
    required String resourcePath,
  });

  Future<String> crateApiDocumentReadEpubSection({
    required String path,
    required BigInt sectionIndex,
  });

  String crateApiDocumentReadEpubSectionSync({
    required String path,
    required BigInt sectionIndex,
  });

  Future<int?> crateApiDocumentResolveEpubSpineHref({
    required String path,
    required String href,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<RustLogEntry> crateApiInitCreateLogStream() {
    final s = RustStreamSink<RustLogEntry>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_rust_log_entry_Sse(s, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiInitCreateLogStreamConstMeta,
          argValues: [s],
          apiImpl: this,
        ),
      ),
    );
    return s.stream;
  }

  TaskConstMeta get kCrateApiInitCreateLogStreamConstMeta =>
      const TaskConstMeta(debugName: "create_log_stream", argNames: ["s"]);

  @override
  RustExtractedContent crateApiTtsExtractHtmlContent({required String html}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(html, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_extracted_content,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTtsExtractHtmlContentConstMeta,
        argValues: [html],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsExtractHtmlContentConstMeta =>
      const TaskConstMeta(
        debugName: "extract_html_content",
        argNames: ["html"],
      );

  @override
  Future<BigInt> crateApiDocumentGetCbzPageCount({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentGetCbzPageCountConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentGetCbzPageCountConstMeta =>
      const TaskConstMeta(debugName: "get_cbz_page_count", argNames: ["path"]);

  @override
  List<String> crateApiDocumentGetCbzPagePaths({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentGetCbzPagePathsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentGetCbzPagePathsConstMeta =>
      const TaskConstMeta(debugName: "get_cbz_page_paths", argNames: ["path"]);

  @override
  Future<RustDocumentMetadata> crateApiDocumentGetEpubMetadata({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_document_metadata,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentGetEpubMetadataConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentGetEpubMetadataConstMeta =>
      const TaskConstMeta(debugName: "get_epub_metadata", argNames: ["path"]);

  @override
  Future<BigInt> crateApiDocumentGetEpubSectionCount({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentGetEpubSectionCountConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentGetEpubSectionCountConstMeta =>
      const TaskConstMeta(
        debugName: "get_epub_section_count",
        argNames: ["path"],
      );

  @override
  Future<List<String>> crateApiDocumentGetEpubSpineHrefs({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentGetEpubSpineHrefsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentGetEpubSpineHrefsConstMeta =>
      const TaskConstMeta(
        debugName: "get_epub_spine_hrefs",
        argNames: ["path"],
      );

  @override
  Future<List<RustTocItem>> crateApiDocumentGetEpubToc({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_toc_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentGetEpubTocConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentGetEpubTocConstMeta =>
      const TaskConstMeta(debugName: "get_epub_toc", argNames: ["path"]);

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiInitIsRustInitialized() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitIsRustInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitIsRustInitializedConstMeta =>
      const TaskConstMeta(debugName: "is_rust_initialized", argNames: []);

  @override
  String crateApiTtsNormalizeSingleTextForSpeech({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTtsNormalizeSingleTextForSpeechConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsNormalizeSingleTextForSpeechConstMeta =>
      const TaskConstMeta(
        debugName: "normalize_single_text_for_speech",
        argNames: ["text"],
      );

  @override
  List<RustTtsChunk> crateApiTtsPreprocessTextForTts({
    required String text,
    required int sectionIndex,
    String? language,
    required bool isHtml,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_i_32(sectionIndex, serializer);
          sse_encode_opt_String(language, serializer);
          sse_encode_bool(isHtml, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_tts_chunk,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTtsPreprocessTextForTtsConstMeta,
        argValues: [text, sectionIndex, language, isHtml],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsPreprocessTextForTtsConstMeta =>
      const TaskConstMeta(
        debugName: "preprocess_text_for_tts",
        argNames: ["text", "sectionIndex", "language", "isHtml"],
      );

  @override
  Uint8List crateApiDocumentReadCbzAssetSync({
    required String path,
    required String assetPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(assetPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentReadCbzAssetSyncConstMeta,
        argValues: [path, assetPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentReadCbzAssetSyncConstMeta =>
      const TaskConstMeta(
        debugName: "read_cbz_asset_sync",
        argNames: ["path", "assetPath"],
      );

  @override
  Future<Uint8List> crateApiDocumentReadCbzPageImage({
    required String path,
    required BigInt pageIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_usize(pageIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentReadCbzPageImageConstMeta,
        argValues: [path, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentReadCbzPageImageConstMeta =>
      const TaskConstMeta(
        debugName: "read_cbz_page_image",
        argNames: ["path", "pageIndex"],
      );

  @override
  Uint8List crateApiDocumentReadCbzPageImageSync({
    required String path,
    required BigInt pageIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_usize(pageIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentReadCbzPageImageSyncConstMeta,
        argValues: [path, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentReadCbzPageImageSyncConstMeta =>
      const TaskConstMeta(
        debugName: "read_cbz_page_image_sync",
        argNames: ["path", "pageIndex"],
      );

  @override
  Future<Uint8List> crateApiDocumentReadEpubResource({
    required String path,
    required String resourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(resourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentReadEpubResourceConstMeta,
        argValues: [path, resourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentReadEpubResourceConstMeta =>
      const TaskConstMeta(
        debugName: "read_epub_resource",
        argNames: ["path", "resourcePath"],
      );

  @override
  Uint8List crateApiDocumentReadEpubResourceSync({
    required String path,
    required String resourcePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(resourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentReadEpubResourceSyncConstMeta,
        argValues: [path, resourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentReadEpubResourceSyncConstMeta =>
      const TaskConstMeta(
        debugName: "read_epub_resource_sync",
        argNames: ["path", "resourcePath"],
      );

  @override
  Future<String> crateApiDocumentReadEpubSection({
    required String path,
    required BigInt sectionIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_usize(sectionIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentReadEpubSectionConstMeta,
        argValues: [path, sectionIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentReadEpubSectionConstMeta =>
      const TaskConstMeta(
        debugName: "read_epub_section",
        argNames: ["path", "sectionIndex"],
      );

  @override
  String crateApiDocumentReadEpubSectionSync({
    required String path,
    required BigInt sectionIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_usize(sectionIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentReadEpubSectionSyncConstMeta,
        argValues: [path, sectionIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentReadEpubSectionSyncConstMeta =>
      const TaskConstMeta(
        debugName: "read_epub_section_sync",
        argNames: ["path", "sectionIndex"],
      );

  @override
  Future<int?> crateApiDocumentResolveEpubSpineHref({
    required String path,
    required String href,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(href, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_i_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentResolveEpubSpineHrefConstMeta,
        argValues: [path, href],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentResolveEpubSpineHrefConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_epub_spine_href",
        argNames: ["path", "href"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<RustLogEntry> dco_decode_StreamSink_rust_log_entry_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustFootnote> dco_decode_list_rust_footnote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_footnote).toList();
  }

  @protected
  List<RustTocItem> dco_decode_list_rust_toc_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_toc_item).toList();
  }

  @protected
  List<RustTtsChunk> dco_decode_list_rust_tts_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_tts_chunk).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  RustDocumentMetadata dco_decode_rust_document_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RustDocumentMetadata(
      title: dco_decode_opt_String(arr[0]),
      author: dco_decode_opt_String(arr[1]),
      language: dco_decode_opt_String(arr[2]),
      identifier: dco_decode_opt_String(arr[3]),
      publisher: dco_decode_opt_String(arr[4]),
      description: dco_decode_opt_String(arr[5]),
      coverImagePath: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  RustExtractedContent dco_decode_rust_extracted_content(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustExtractedContent(
      displayText: dco_decode_String(arr[0]),
      speechText: dco_decode_String(arr[1]),
      footnotes: dco_decode_list_rust_footnote(arr[2]),
    );
  }

  @protected
  RustFootnote dco_decode_rust_footnote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustFootnote(
      id: dco_decode_String(arr[0]),
      contentHtml: dco_decode_String(arr[1]),
      footnoteType: dco_decode_String(arr[2]),
    );
  }

  @protected
  RustLogEntry dco_decode_rust_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustLogEntry(
      timeMillis: dco_decode_i_64(arr[0]),
      level: dco_decode_i_32(arr[1]),
      tag: dco_decode_String(arr[2]),
      msg: dco_decode_String(arr[3]),
    );
  }

  @protected
  RustTocItem dco_decode_rust_toc_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustTocItem(
      title: dco_decode_String(arr[0]),
      href: dco_decode_String(arr[1]),
      level: dco_decode_usize(arr[2]),
      chapterIndex: dco_decode_opt_box_autoadd_i_32(arr[3]),
      children: dco_decode_list_rust_toc_item(arr[4]),
    );
  }

  @protected
  RustTtsChunk dco_decode_rust_tts_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RustTtsChunk(
      id: dco_decode_String(arr[0]),
      sectionIndex: dco_decode_i_32(arr[1]),
      sentenceIndex: dco_decode_i_32(arr[2]),
      displayText: dco_decode_String(arr[3]),
      spokenText: dco_decode_String(arr[4]),
      startOffset: dco_decode_usize(arr[5]),
      endOffset: dco_decode_usize(arr[6]),
      estimatedDurationMs: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<RustLogEntry> sse_decode_StreamSink_rust_log_entry_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustFootnote> sse_decode_list_rust_footnote(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustFootnote>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_footnote(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustTocItem> sse_decode_list_rust_toc_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustTocItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_toc_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustTtsChunk> sse_decode_list_rust_tts_chunk(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustTtsChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_tts_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustDocumentMetadata sse_decode_rust_document_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_identifier = sse_decode_opt_String(deserializer);
    var var_publisher = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_coverImagePath = sse_decode_opt_String(deserializer);
    return RustDocumentMetadata(
      title: var_title,
      author: var_author,
      language: var_language,
      identifier: var_identifier,
      publisher: var_publisher,
      description: var_description,
      coverImagePath: var_coverImagePath,
    );
  }

  @protected
  RustExtractedContent sse_decode_rust_extracted_content(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayText = sse_decode_String(deserializer);
    var var_speechText = sse_decode_String(deserializer);
    var var_footnotes = sse_decode_list_rust_footnote(deserializer);
    return RustExtractedContent(
      displayText: var_displayText,
      speechText: var_speechText,
      footnotes: var_footnotes,
    );
  }

  @protected
  RustFootnote sse_decode_rust_footnote(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_contentHtml = sse_decode_String(deserializer);
    var var_footnoteType = sse_decode_String(deserializer);
    return RustFootnote(
      id: var_id,
      contentHtml: var_contentHtml,
      footnoteType: var_footnoteType,
    );
  }

  @protected
  RustLogEntry sse_decode_rust_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeMillis = sse_decode_i_64(deserializer);
    var var_level = sse_decode_i_32(deserializer);
    var var_tag = sse_decode_String(deserializer);
    var var_msg = sse_decode_String(deserializer);
    return RustLogEntry(
      timeMillis: var_timeMillis,
      level: var_level,
      tag: var_tag,
      msg: var_msg,
    );
  }

  @protected
  RustTocItem sse_decode_rust_toc_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_level = sse_decode_usize(deserializer);
    var var_chapterIndex = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_children = sse_decode_list_rust_toc_item(deserializer);
    return RustTocItem(
      title: var_title,
      href: var_href,
      level: var_level,
      chapterIndex: var_chapterIndex,
      children: var_children,
    );
  }

  @protected
  RustTtsChunk sse_decode_rust_tts_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sectionIndex = sse_decode_i_32(deserializer);
    var var_sentenceIndex = sse_decode_i_32(deserializer);
    var var_displayText = sse_decode_String(deserializer);
    var var_spokenText = sse_decode_String(deserializer);
    var var_startOffset = sse_decode_usize(deserializer);
    var var_endOffset = sse_decode_usize(deserializer);
    var var_estimatedDurationMs = sse_decode_u_32(deserializer);
    return RustTtsChunk(
      id: var_id,
      sectionIndex: var_sectionIndex,
      sentenceIndex: var_sentenceIndex,
      displayText: var_displayText,
      spokenText: var_spokenText,
      startOffset: var_startOffset,
      endOffset: var_endOffset,
      estimatedDurationMs: var_estimatedDurationMs,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_rust_log_entry_Sse(
    RustStreamSink<RustLogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_log_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_footnote(
    List<RustFootnote> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_footnote(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_toc_item(
    List<RustTocItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_toc_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_tts_chunk(
    List<RustTtsChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_tts_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_document_metadata(
    RustDocumentMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_String(self.identifier, serializer);
    sse_encode_opt_String(self.publisher, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.coverImagePath, serializer);
  }

  @protected
  void sse_encode_rust_extracted_content(
    RustExtractedContent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.displayText, serializer);
    sse_encode_String(self.speechText, serializer);
    sse_encode_list_rust_footnote(self.footnotes, serializer);
  }

  @protected
  void sse_encode_rust_footnote(RustFootnote self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.contentHtml, serializer);
    sse_encode_String(self.footnoteType, serializer);
  }

  @protected
  void sse_encode_rust_log_entry(RustLogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timeMillis, serializer);
    sse_encode_i_32(self.level, serializer);
    sse_encode_String(self.tag, serializer);
    sse_encode_String(self.msg, serializer);
  }

  @protected
  void sse_encode_rust_toc_item(RustTocItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_usize(self.level, serializer);
    sse_encode_opt_box_autoadd_i_32(self.chapterIndex, serializer);
    sse_encode_list_rust_toc_item(self.children, serializer);
  }

  @protected
  void sse_encode_rust_tts_chunk(RustTtsChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_32(self.sectionIndex, serializer);
    sse_encode_i_32(self.sentenceIndex, serializer);
    sse_encode_String(self.displayText, serializer);
    sse_encode_String(self.spokenText, serializer);
    sse_encode_usize(self.startOffset, serializer);
    sse_encode_usize(self.endOffset, serializer);
    sse_encode_u_32(self.estimatedDurationMs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
